• remove the old v5 binary • let tm_dialog point to the update at http://macromates.com/blog/archives/2006/10/28/new-dialog-system-for-commands/ when called outside TextMate
git-svn-id: http://macromates.com/svn/Bundles/trunk@6936 dfb7d73b-c2ec-0310-8fea-fb051d288c6d

diff --git a/Support/bin/tm_dialog b/Support/bin/tm_dialog
--- a/Support/bin/tm_dialog
+++ b/Support/bin/tm_dialog
@@ -2,5 +2,5 @@
 
 if [[ -e "$DIALOG" ]]
 	then "$DIALOG" "$@"
-	else "$TM_SUPPORT_PATH/bin/tm_dialog_v5" "$@"
+	else echo 1>&2 "ERROR: Please read the 2007-03-15 update at http://macromates.com/blog/archives/2006/10/28/new-dialog-system-for-commands/"
 fi
